### PR TITLE
[ENH] Neat and automated transfer learning with OPTIMADE API for auto-adjusted problem-specific ML model generation on the fly

### PR DESCRIPTION
**Pull request by amkrajewski**
As the title says, this new addition to the core `pySIPFENN` functionalities connects it to OPTIMADE API to enable rapid adjustment of the models to any specific dataset described by an OPTIMADE query (or multiple queries). Most of the functions are neatly hidden behind high-level API and default values should work well for datasets between 100-10,000 datapoints. 

You can now simply:
```python
from pysipfenn import Calculator, OPTIMADEAdjuster
c = Calculator(autoLoad=False)
c.loadModels("SIPFENN_Krajewski2022_NN30")
ma = OPTIMADEAdjuster(c, "SIPFENN_Krajewski2022_NN30",  useClearML=True, device='mps') # MPS is for Apple M1 GPU

ma.fetchAndFeturize(
    'elements HAS "Hf" AND elements HAS "Mo" AND NOT elements HAS ANY "O","C","F","Cl","S"',
    parallelWorkers=4)
ma.adjust()

ma.plotStarting() # See the starting performance
ma.plotAdjusted() # See the adjusted performance
```
or to perform a hyperparameter search, replace the `ma.adjust()` with:
```python
ma.matrixHyperParameterSearch()
ma.adjust(learningRate=0.0001, optimizer='AdamW', weightDecay=1e-05, epochs=37)
```

All model usage works as before with the `Calculator` class. Modifying or exporting it for later is through specific classes in the `modelExporters` submodule.

### CODE REVIEW

**Comment by amkrajewski** [comment]
Notes:
1. It is feature-complete.
2. I'm still working on the testing suite.
3. @rdamaral will add a neat tutorial at a future date.

**Comment by amkrajewski** [comment]
Hi @jwsiegel2510 and @rdamaral Everything is complete and the tests are passing. It's ready to be reviewed!

**Comment by amkrajewski** [comment]
Hi @jwsiegel2510 and @rdamaral, I was hoping to pull it later today to align with the manuscript posting on arXiv.

**Comment by rdamaral** [comment]
Hi Adam,

I've reviewed the documentation, tested the main functions, and they are working well. I also did not encounter any issues when installing this branch version in a new conda environment (Python 3.10). 

Just a couple of comments:

- Running the hyperparameter search step takes a long time on a cpu, so I couldn't finish testing. As discussed, please consider changing the default epochs to a lower value. 
- When testing OPTIMADE providers:
> OQMD returned ``TypeError: can only concatenate str (not "int") to str`` 
> JARVIS returned ``ValidationError: 1 validation error for StructureResource``. 
> Aflow returned ``Error: Provider ...: ('Connection aborted.', ... ))``
PS: Both OQMD and Jarvis were run using the ``targetPath`` values mentioned in the documentation. Other than these, MP and Alexandria were also tested and did not raise any error. 
- I also tried providing the wrong targetPath for a provider and it raises: ``'ValueError: not enough values to unpack (expected 4, got 0)'``. Do you think we ``targetPath`` could be fetched automatically from each provider's endpoint when defyining OPTIMADEAdjuster? I'm considering this because even the current default values may eventually break, for instance, if MP decides to change their endpoint (again). Another alternative would be to have ``targetPath`` set to () rather than ``MP``'s formation energy path.

**Comment by amkrajewski** [comment]
Hi @rdamaral ! Thanks for insightful comments :) 

1. The default number of epochs for fine-tuning was reduced to `20`, with documentation discussing this and mentioning that on a GPU (even a laptop one) `100` may be preferred.
2. `OQMD` server is down and `JARVIS` seems to have issues filtering. I will ask about that at the developer meeting tomorrow.
3. I've added a bunch of assertions that should catch unexpected user inputs and display useful messages on what went wrong. The property data paths are provider-specific and cannot be inferred a prior.

**Comment by amkrajewski** [comment]
I also added a new functionality that allows you to override `provider` and use a custom endpoint. E.g.
```python
ma = pysipfenn.OPTIMADEAdjuster(
    c,
    model="SIPFENN_Krajewski2022_NN30",
    endpointOverride=["https://alexandria.icams.rub.de/pbesol"],
    targetPath=['attributes', '_alexandria_formation_energy_per_atom']
)

ma.fetchAndFeturize(
    'elements HAS "Hf" AND elements HAS "Mo" AND elements HAS "Zr"',
    parallelWorkers=2
)
```

**Comment by rdamaral** [comment]
Nice. The ``endpointOverride`` input is very interesting from the user’s perspective, especially in the event of changes or new additions to OPTIMADE. 👍

**Review by jwsiegel2510 — COMMENTED** [review]
Looks good to me

**Review by jwsiegel2510 — COMMENTED** [review]
Looks good to me, I guess the previous two commits were meant to be one.

**Pull request merged**
