### PR TITLE
[add] modelExporters 

### PR DESCRIPTION
**Pull request by amkrajewski**
- This PR introduces the `modelExporters` module with 3 Exporter classes, allowing conversion and saving of the loaded models (including ones modified within pySIPFENN transfer learning runs) into ONNX, PyTorch, and CoreML formats.
- The `ONNXExporter` also allows for model conversion to FP16 precision, lowering the size by a factor of 2, as well as model simplification with the ONNX optimizer toolset.

### CODE REVIEW

**Comment by amkrajewski** [comment]
TODO:
- Testing the runtime of the 3 exporters
- Usage examples in the docs.

**Review by jwsiegel2510 — APPROVED** [review]
This looks good to me.

**Review by jwsiegel2510 — APPROVED** [review]
So if the calculator is empty it is not an error?

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Review by jwsiegel2510 — APPROVED** [review]

**Comment by amkrajewski** [comment]
> So if the calculator is empty it is not an error?

Based on the current PR state, it *does* raise an AssertionError with the message 'No models loaded in calculator. Nothing to export.' 

I will add tests to verify these errors occur as intended.

**Comment by amkrajewski** [comment]
I added the aforementioned tests and documentation page on why-and-how to use Exporters.

**Pull request merged**
